#! /bin/sh
bspc config border_width        1
bspc config window_gap         30
bspc config top_padding        22
bspc config left_padding       0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config normal_border_color "#800000"
bspc config active_border_color "#b30000"
bspc config focused_border_color "#990000"
bspc config presel_border_color "#a10202"
bspc config urgent_border_color "#ff3333"
bspc config focused_locked_border_color "#9f0000"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config focus_follows_pointer true

bspc monitor DFP10 -n "Primary" -d "1" "2" "3" "4"
bspc monitor DFP5 -n "Secondary" -d "5" "6" "7"

bspc rule -a Firefox border=off

################################################################################
#                             X Server stuff                                   #
################################################################################
xsetroot -cursor_name left_ptr

#merge resources
xrdb -merge ~/.Xresources

#keyboard stuff
#https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg
setxkbmap -option caps:swapescape
setxkbmap -layout us,gr -option grp:alt_shift_toggle

################################################################################

################################################################################
## autostart
################################################################################
unclutter -root -idle 5 &
nitrogen --restore &
dunst -config $HOME/.config/dunstrc  &

#compton composition manager
compton &

#audioz
pulseaudio --start
./current_song &

#panel
cd $HOME/.config/bspwm/panel/ && ./panel &
